### ISSUE TITLE
Turning references into citations

### ISSUE THREAD

**Issue by langner** [ContentMine/journal-scrapers#31]
Since references are parsed in principle, I wonder how hard it would be to turn them into citations for the referenced articles. Has anyone looked into this?

**Comment by Blahah** [comment]
Can you explain what you mean by turning references into citations? In my understanding of the terms they are interchangeable - a reference is a citation.

**Comment by langner** [comment]
> Can you explain what you mean by turning references into citations? In my understanding of the terms they are interchangeable - a reference is a citation.

Yes, but the references are often in a shorter format, so I would think connecting references to specific articles is not automatic.

**Comment by Blahah** [comment]
OK - what we capture is the reference list that usually occurs at the end of the document. We capture it in plain HTML, so that a user can parse it to extract out the structure if they like. We don't offer any post-processing of that captured HTML, as that's beyond the score of a scraper. However, the raw materials for someone to do that processing are there.

**Comment by langner** [comment]
Good point, it is beyond the scope of a scraper. Any idea if someone has tried this already?

**Comment by Blahah** [comment]
I don't know of anyone who has done it with the results of a `journal-scraper` (although some colleagues and I are about to start doing a research project that will parse scraped references). However, lots of people do this in general with references. There are dozens of pieces of software for semantic parsing of references, and it's fairly simple to look up the results somewhere like the CrossRef API to get links to canonical records.

**Comment by langner** [comment]
OK, thanks. Closing this then.
